Replace lambda with method reference in SpringBootGenerator (#3371)
eclipse-jkube/jkube pull request #3443
Opened 2024-10-09 18:03 UTC by Aryant-Tripathi

- This pull request addresses issue #3371, which suggests replacing lambda expressions with method references where applicable in the SpringBootGenerator. Method references offer more concise syntax and can improve readability.

**Changes:**

- Refactored lambda expressions that can be simplified by method references.
- Updated occurrences where method references provide cleaner and more efficient code, ensuring no changes to the functionality of the SpringBootGenerator.

2024-10-09 18:03 UTC, manusa commented
<!-- Eclipse JKube CI bot report -->
<!-- METADATA {"pr":"3443","runId":"11260515588"} -->
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3443 (_2024-10-09T18:03:21Z_)

:gear: [JKube E2E Tests (11260515588)](https://github.com/eclipse-jkube/ci/actions/runs/11260515588) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3443)](https://github.com/eclipse-jkube/ci/actions/runs/11260515588/job/31311909368)

2024-10-10 03:57 UTC, rohanKanojia commented
Could you please check why build is failing on JDK8 ?

2024-10-10 16:03 UTC, Aryant-Tripathi commented
Yes sure, checked with the issue and got error as:  **incompatible types: invalid method reference**

Attaching screenshot for reference: 
<img width="994" alt="Screenshot 2024-10-10 at 21 27 43" src="https://github.com/user-attachments/assets/36daa328-c6bf-4082-b465-664272639107">
-------

I am wondering If we can do something like this: 
```
    @Override
    protected Map<String, String> getEnv(boolean prePackagePhase) {
        return nestedGenerator.getEnv(this::fetchEnv, prePackagePhase);
    }
    
    protected Map<String, String> fetchEnv(boolean prePackagePhase) {
        return super.getEnv(prePackagePhase);
    }
```

2024-10-11 16:04 UTC, Aryant-Tripathi commented
@manusa @rohanKanojia Gentle ping, Do I need to proceed with suggestion ?

2024-10-14 04:42 UTC, manusa requested changes
Sorry for the late reply.
The issue definition is wrong since it's incompatible with Java8.
Let's just remove the warning.

2024-10-14 04:42 UTC, manusa commented on jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java
> +        return nestedGenerator.getEnv(super::getEnv, prePackagePhase);
Apparently, the statement is incompatible with Java 8.
Let's just remove the warning and delay the refactoring to the future:
```suggestion
      //TODO: Java8 compatibility, remove warning. Remove annotation once baseline is set to Java11+
      //noinspection Convert2MethodRef
      return nestedGenerator.getEnv(ppp -> super.getEnv(ppp), prePackagePhase);
```

2024-10-14 17:15 UTC, Aryant-Tripathi commented
@manusa Updated with the suggestion :)

2024-10-16 04:00 UTC, rohanKanojia approved these changes

2024-10-16 09:40 UTC, manusa approved these changes
LGTM, thx!

2024-10-16 09:40 UTC, merged